id: P009390
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:36:31.351240
source_metadata:
  id: bdr:W1AC389
  title: 'ཕྱག་རྫོགས་ཟུང་འཇུག་ཐུགས་རྗེ་ཆེན་པོའི་དམར་ཁྲིད་ཀྱི་རྒྱབ་ཆོས། '
  author: ''
  volumes:
    60dcd4ab0db04548afcdff7c3b418312:
      image_group_id: I2PD18245
      title: ''
      volume_number: 1
      total_pages: 286
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
